import javax.swing.*;
import java.awt.*;
public class CalculatorTwoGUI {
    public JFrame frame;
    public JPanel panel;
    public JButton one;
    public JButton two;
    public JButton three;
    public JButton four;
    public JButton five;
    public JButton six;
    public JButton seven;
    public JButton eight;
    public JButton nine;
    public JButton zero;
    public JButton clear;
    public JButton equal;
    public JButton plusButton;
    public JButton minusButton;
    public JButton multiplyButton;
    public JButton divideButton;
    public JTextField field1;
    public CalculatorTwoGUI(){
        frame = new JFrame("My Calculator");
        panel = new JPanel();
        one = new JButton("1");
        two = new JButton("2");
        three = new JButton("3");
        four = new JButton("4");
        five = new JButton("5");
        six = new JButton("6");
        seven = new JButton("7");
        eight = new JButton("8");
        nine = new JButton("9");
        zero = new JButton("0");
        clear = new JButton("c");
        equal = new JButton("=");
        plusButton = new JButton("+");
        minusButton = new JButton("-");
        multiplyButton = new JButton("×");
        divideButton = new JButton("/");
        field1 = new JTextField();
        frame.setLayout(new BorderLayout());
        frame.add(field1,BorderLayout.NORTH);
        panel.setLayout(new GridLayout(4,4));
        panel.add(seven);
        panel.add(eight);
        panel.add(nine);
        panel.add(plusButton);
        panel.add(four);
        panel.add(five);
        panel.add(six);
        panel.add(minusButton);
        panel.add(one);
        panel.add(two);
        panel.add(three);
        panel.add(multiplyButton);
        panel.add(zero);
        panel.add(clear);
        panel.add(equal);
        panel.add(divideButton);
        frame.add(panel,BorderLayout.CENTER);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(300, 300);
        frame.setVisible(true);
    }
}
